---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'

dependencies:
  ansible_core:
    package_pip: ansible-core==2.14.4
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python: requirements.txt
  system:
    - iputils-ping [platform:deb]
    - genisoimage [platform:deb]
  # exclude:
  #   python:
  #     - docker

images:
  base_image:
    name: ubuntu:latest

# Custom package manager path for the Ubuntu based images
# options:
#  package_manager_path: /usr/bin/apt-get

# additional_build_files:
#   - src: files/ansible.cfg
#     dest: configs

additional_build_steps:
  prepend_base:
    - RUN echo This is a prepend base command!
    - RUN apt-get update && apt-get install -y git

  prepend_final: |
    RUN whoami
    RUN cat /etc/os-release
  append_final:
    - RUN echo This is a post-install command!
    - RUN ls -la /etc
