name: Ansible Builder

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  create-docker-image:
    name: create-image
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'

      - name: Install ansible-builder
        run: pip install ansible-builder==3.1.0

      - name: Build Ansible Execution Environment
        run: ansible-builder build -f execution-environment.yml --container-runtime=docker

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and Push Docker image to Docker Hub
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)
          docker tag ansible-execution-env:latest ${{ secrets.DOCKER_USERNAME }}/ansible-execution-env:${BRANCH_NAME}
          docker push ${{ secrets.DOCKER_USERNAME }}/ansible-execution-env:${BRANCH_NAME}